project:
  type: website

website:
  title: "Vidal's Math Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes/example.qmd
        text: Notes

format:
  html:
    theme: darkly
    toc: true
